name: sets_deb_build

services:
  sets_deb_build:
    image: deb_build_base
    build:
      context: ../..
      dockerfile: distribution/debian/deb_build_base.Dockerfile
    container_name: running_sets_deb_build
    volumes:
      - type: bind
        source: ../../
        target: /mnt/
        read_only: false
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p /build
        cd /build
        cp -r /mnt/distribution/ /mnt/local/ /mnt/src/ /mnt/main.py /mnt/pyproject.toml /mnt/LICENSE /mnt/README.md ./
        distribution/build_pyinstaller.sh
        distribution/debian/package_deb.sh
        mkdir -p /mnt/dist
        cp dist/sets.deb /mnt/dist/sets.deb
