name: sets_deb_build

services:
  deb_build_base:
    image: deb_build_base
    build:
      context: ../..
      dockerfile: distribution/debian/deb_build_base.Dockerfile

  sets_deb_build:
    depends_on:
      deb_build_base:
        condition: service_completed_successfully
    image: setsdeb
    build:
      context: ../..
      dockerfile: distribution/debian/build_deb.Dockerfile
    container_name: running_sets_deb_build
    volumes:
      - type: bind
        source: ../../dist/
        target: /mnt/
        read_only: false
    command:
      - /bin/sh
      - -c
      - |
        cd /build
        distribution/build_pyinstaller.sh
        distribution/debian/package_deb.sh
        cp dist/sets.deb /mnt/sets.deb
